const getters = {
  noticeDetailVuex: (state) => state.notice.noticeDetailVuex,
  tag: (state) => state.tags.tag,
  language: (state) => state.common.language,
  website: (state) => state.common.website,
  userInfo: (state) => state.user.userInfo,
  status: (state) => state.user.info.status,
  userId: (state) => state.user.userInfo.user_id,
  companyId: (state) => state.user.userInfo.company_id,
  colorName: (state) => state.common.colorName,
  themeName: (state) => state.common.themeName,
  isShade: (state) => state.common.isShade,
  isCollapse: (state) => state.common.isCollapse,
  keyCollapse: (state, getters) => (getters.screen > 1 ? getters.isCollapse : false),
  screen: (state) => state.common.screen,
  isLock: (state) => state.common.isLock,
  isFullScren: (state) => state.common.isFullScren,
  isMenu: (state) => state.common.isMenu,
  lockPasswd: (state) => state.common.lockPasswd,
  tagList: (state) => state.tags.tagList,
  tagWel: (state) => state.tags.tagWel,
  token: (state) => state.user.token,
  roles: (state) => state.user.roles,
  privileges: (state) => state.user.privileges,
  menu: (state) => state.user.menu,
  tenantContent: (state) => state.user.tenantContent,
  menuAll: (state) => state.user.menuAll,
  menuLoading: (state) => state.user.menuLoading,
  logsList: (state) => state.logs.logsList,
  logsLen: (state) => state.logs.logsList.length || 0,
  logsFlag: (state, getters) => getters.logsLen === 0,
  flowRoutes: (state) => state.dict.flowRoutes,
  fieldList: (state) => state.process.fieldList,
  processData: (state) => state.process.processData
}
export default getters
