<template>
  <div>
    <keep-alive>
      <router-view
        v-if="$route.meta.$keepAlive"
        class="avue-view"
      />
    </keep-alive>
    <router-view
      v-if="!$route.meta.$keepAlive"
      class="avue-view"
    />
  </div>
</template>
